### ISSUE TITLE
Test message resolvers aren't returning null

### ISSUE THREAD

**Issue by ultraq** [thymeleaf/thymeleaf-testing#9]
As discovered in the forums: http://forum.thymeleaf.org/messages-msgOrNull-returns-message-en-and-not-null-td4028187.html

Looks like `org.thymeleaf.testing.templateengine.messages.TestMessages` isn't returning `null` when it should, instead generating the 'absent message' string.

**Comment by ultraq** [comment]
Hmm, we don't have tests for our testing framework do we @danielfernandez ? (tests for tests! :D)

**Comment by danielfernandez** [comment]
Oops... no, we don't have tests for this :-)

Looking at your fix at https://github.com/thymeleaf/thymeleaf-testing/commit/292d7d40e7b621e94768b592db1fd3e160236302 ... have you checked that this does not affect `MessageExpression`s? this is, that the resolution of inexistent messages in `#{...}` expressions --instead of using `#messages`-- still works the same way (in tests)?

**Comment by ultraq** [comment]
Just gave it a try using this test file

```
%MESSAGES

%INPUT
<!DOCTYPE html>
<html>
    <body>
        <p th:text="#{message}"></p>
    </body>
</html>

%OUTPUT 
<!DOCTYPE html>
<html>
    <body>
        <p></p>
    </body>
</html>
```

Test error (expected):

```
Obtained:
[  <body>
        <p>??message_en??</p>
    </body>
</h]
at line 5 col 12, but expected:
[  <body>
        <p></p>
    </body>
</h]
```

So a non-existent message still gives the `??message_en??` block, which is what's expected from the standard message expression, which is good.

**Comment by danielfernandez** [comment]
Perfect. Can you then merge with `2.1-master` and deploy a new snapshot? :)

**Comment by ultraq** [comment]
Merge done, but I'm having trouble deploying to the snapshot repositories.  Could you give it a try?

**Comment by danielfernandez** [comment]
Done! :-)

Updated 2.1.4-SNAPSHOT
